# Application Configuration
app:
  name: "CureConnect Medical Tourism Portal"
  version: "1.0.0"
  environment: "development"  # development, production
  debug: true
  timezone: "Asia/Kolkata"

  # URLs and Paths
  base_url: "http://localhost/CureConnect"
  assets_url: "http://localhost/CureConnect"
  uploads_url: "http://localhost/CureConnect/uploads"

  # File Paths
  templates_path: "templates"
  cache_path: "var/cache"
  logs_path: "var/logs"
  uploads_path: "uploads"

  # Security
  session:
    lifetime: 7200  # 2 hours in seconds
    name: "CURECONNECT_SESSION"
    secure: false   # Set to true in production with HTTPS
    httponly: true
    samesite: "Strict"

  csrf:
    token_name: "csrf_token"

  # Internationalization
  localization:
    default_language: "en"
    supported_languages: ["en", "bn", "ar"]
    fallback_language: "en"

  # Email Configuration
  mail:
    from_email: "info@cureconnect.in"
    from_name: "CureConnect Support"
    reply_to: "support@cureconnect.in"

